# коментарий .
# Сначало ставим версию докер композера
version: "3.3"

# Тут дальше идет какие мы сервисы хотим запустить.Так назваемая инструкция
# Название сервисов может быть любыми, но что бы было логически понятно какие там инструкции будут php: или mysql:
services:
  web:
    image: nginx:1.19.6
    ports:
      - "8080:80"
    volumes:
      # Указываем где находится конфиги на nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Прописываем путь к нашему проэкту и контенера
      - ./:/var/www/project

  # Если нам надо просто запусить с докерХаба то можем использовать команду image:
  # А если собрать свой собственый то указываем путь на докерфаил на инструкции
  php:
    build: ./docker/php
    ports:
      - "9000:9000"
    expose:
      - 9000
    volumes:
      # Прописываем путь к нашему проэкту и контенера
      - ./:/var/www/project
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  # База данных
  mysql:
    # Что мы берем образ с докерХаба
    image: mysql:8.0.23
    # Указываем порты или лутчес случае сылку на .env
    # Тут сказано если неуказан порт в конфиге то запускаем по умолчаниию  3306
    ports:
      - "3306:3306"
    # Тут прописываем параметры для бв
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
      MYSQL_DATABASE:  ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: "yes"
    volumes:
      # Указываем где хранится бд
      - mysql_data:/var/lib/mysql
    # Подключение .env файла к бд
    env_file:
      - .env

# Создаем волюм в докере что бы все данные хранились в докере
volumes:
  mysql_data: